/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.DAO.Conexion;
import Modelo.Vo.IngredienteVo;
import Modelo.Vo.PizzaVo;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author santi
 */
public class FormularioP extends javax.swing.JFrame {

    /**
     * Creates new form ForumarioP
     */
    protected static List<IngredienteVo> ingredientes;
    protected static List<PizzaVo> pizzaVo;

    public FormularioP() throws SQLException, ClassNotFoundException {
        initComponents();
        ingredientes = new ArrayList<>();
        pizzaVo = new ArrayList<>();
        cargarIngredientes();
        cargarPizzas();

        this.setSize(1020, 680);

        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Vista/imagenes/iconos/principal_1.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        comandabtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        GenerarArchivo = new javax.swing.JMenuItem();
        Editar = new javax.swing.JMenu();
        NuevoIngrediente = new javax.swing.JMenuItem();
        ModificarP = new javax.swing.JMenuItem();
        NuevaPizza = new javax.swing.JMenuItem();
        Eventos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        Historial = new javax.swing.JMenu();

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        jButton3.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SISTEMA MIA PIZZA");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        jLabel1.setText("PORQUE SER CARA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(520, 100, 245, 28);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(79, 88, 0, 0);

        jLabel3.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jLabel3.setText("M I A  P I Z Z A");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 50, 280, 46);

        jLabel4.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 240, 110, 21);

        jLabel5.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        jLabel5.setText("POR QUE LA BUENA COMIDA NO TIENE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(430, 70, 484, 28);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/Linea Gruesa.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(250, 150, 680, 36);

        jLabel8.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jLabel8.setText("E X P R E S S");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 100, 106, 21);

        jLabel9.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 240, 90, 21);

        jLabel10.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(170, 240, 90, 21);

        jLabel11.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(310, 240, 110, 21);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/Linea Gruesa.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 150, 690, 36);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/linea delgada.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(420, 220, 500, 10);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/linea delgada.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(50, 220, 810, 10);

        comandabtn.setBackground(new java.awt.Color(153, 153, 153));
        comandabtn.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        comandabtn.setText("Comanda");
        comandabtn.setBorder(null);
        comandabtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comandabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comandabtnActionPerformed(evt);
            }
        });
        getContentPane().add(comandabtn);
        comandabtn.setBounds(720, 290, 150, 40);
        comandabtn.getAccessibleContext().setAccessibleName("null");

        jTable1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Sabor", "Tamaño", "Porciones", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class, java.lang.Short.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 270, 430, 80);

        jLabel15.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(590, 240, 110, 21);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/LISTAS.png"))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(880, 280, 60, 70);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/DESFENFOQUE.jpg"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, -10, 1050, 740);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/DESFENFOQUE.jpg"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1070, 730);

        Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N

        Archivo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Archivo.setText("Archivo ");
        Archivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Archivo.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N

        GenerarArchivo.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        GenerarArchivo.setText("Generar Archivo");
        GenerarArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Archivo.add(GenerarArchivo);

        Menu.add(Archivo);

        Editar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Editar.setText("Editar");
        Editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Editar.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N

        NuevoIngrediente.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        NuevoIngrediente.setText("Ingresar Nuevo Ingrediente");
        NuevoIngrediente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NuevoIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoIngredienteActionPerformed(evt);
            }
        });
        Editar.add(NuevoIngrediente);

        ModificarP.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        ModificarP.setText("Modificar Pizza");
        ModificarP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModificarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarPActionPerformed(evt);
            }
        });
        Editar.add(ModificarP);

        NuevaPizza.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        NuevaPizza.setText("Ingresar Nueva Pizza");
        NuevaPizza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NuevaPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaPizzaActionPerformed(evt);
            }
        });
        Editar.add(NuevaPizza);

        Menu.add(Editar);

        Eventos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Eventos.setText(" Eventos");
        Eventos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eventos.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jMenuItem1.setText("Venta");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eventos.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jMenuItem2.setText("Compra");
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eventos.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jMenuItem3.setText("Registro de personal");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eventos.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jMenuItem4.setText("Registro de Articulos");
        jMenuItem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eventos.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jMenuItem5.setText("Gastos");
        jMenuItem5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eventos.add(jMenuItem5);

        Menu.add(Eventos);

        Historial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Historial.setText(" Historial");
        Historial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Historial.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        Menu.add(Historial);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public String ingredientes() {

        String msg = "Ingredientes de la pizzeria:\n";

        for (short i = 0; i < this.ingredientes.size(); i++) {

            msg += (i + 1) + "." + ingredientes.get(i).toString() + "\n";

        }

        return msg;

    }


    private void comandabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comandabtnActionPerformed

        Comanda c;
        try {
            c = new Comanda();
            c.setVisible(true);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(FormularioP.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_comandabtnActionPerformed

    private void NuevoIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoIngredienteActionPerformed
        RegistroIngrediente registro = new RegistroIngrediente();
        registro.setVisible(true);


    }//GEN-LAST:event_NuevoIngredienteActionPerformed

    private void NuevaPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaPizzaActionPerformed
        RegistroPizza registro = new RegistroPizza();
        registro.setVisible(true);

    }//GEN-LAST:event_NuevaPizzaActionPerformed

    private void ModificarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarPActionPerformed
        ModificarPizza modificar = new ModificarPizza();
        modificar.setVisible(true);


    }//GEN-LAST:event_ModificarPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormularioP().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FormularioP.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FormularioP.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenu Editar;
    private javax.swing.JMenu Eventos;
    private javax.swing.JMenuItem GenerarArchivo;
    private javax.swing.JMenu Historial;
    public javax.swing.JMenuBar Menu;
    public javax.swing.JMenuItem ModificarP;
    public javax.swing.JMenuItem NuevaPizza;
    public javax.swing.JMenuItem NuevoIngrediente;
    public javax.swing.JButton comandabtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables

    private void cargarIngredientes() throws SQLException, ClassNotFoundException {

        IngredienteVo ingrediente = new IngredienteVo();
        String nombre = "";
        int precio = 0;

        PreparedStatement ps = null;
        ResultSet rs = null;

        Connection c = Conexion.obtener();
        ps = c.prepareStatement("SELECT * FROM ingrediente");
        rs = ps.executeQuery();
        ResultSetMetaData rsmd = rs.getMetaData();

        short cantidadColumnas = (short) rsmd.getColumnCount();

        while (rs.next()) {

            for (short i = 0; i < cantidadColumnas; i++) {

                if (i % 2 == 0) {

                    nombre = (String) rs.getObject(i + 1);
                    ingrediente.setNombre(nombre);

                } else {

                    precio = (int) rs.getObject(i + 1);
                    ingrediente.setPrecio((short) precio);

                    this.ingredientes.add(ingrediente);
                    ingrediente = new IngredienteVo();

                }

            }

        }

    }

    private void cargarPizzas() throws SQLException, ClassNotFoundException {

        PreparedStatement ps = null;
        ResultSet rs;

        Connection c = Conexion.obtener();

        ps = c.prepareStatement("SELECT * FROM pizza");
        rs = ps.executeQuery();
        ResultSetMetaData rsmd = rs.getMetaData();
        short cantidadColumnas = (short) rsmd.getColumnCount();

        
        while(rs.next()){
        
            for (Byte i = 0; i < cantidadColumnas; i++) {
                
                
                
            }
        
        
        }
    }

}
