/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.DAO.Conexion;
import Modelo.DAO.PizzaDAO;
import Modelo.Vo.PizzaVo;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public class RegistroPizza extends javax.swing.JFrame {

    /**
     * Creates new form RegistroPizza
     */
    public RegistroPizza() {
        initComponents();
        this.setTitle("REGISTRO PIZZA");
        this.setSize(560, 500);
        this.setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/Vista/imagenes/iconos/pizzaa.png")).getImage());
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RegistrarPizza = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jLabel3.setText("M I A  P I Z Z A");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel4.setText("Ingredientes");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 180, 140, 28);

        RegistrarPizza.setBackground(new java.awt.Color(153, 153, 153));
        RegistrarPizza.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        RegistrarPizza.setText("Registrar");
        RegistrarPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarPizzaActionPerformed(evt);
            }
        });
        getContentPane().add(RegistrarPizza);
        RegistrarPizza.setBounds(190, 230, 220, 40);

        jLabel5.setBackground(new java.awt.Color(0, 255, 0));
        jLabel5.setFont(new java.awt.Font("Garamond", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("REGISTRO PIZZA");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 60, 190, 46);

        jLabel7.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel7.setText("Nombre");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 120, 90, 21);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(190, 180, 220, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(190, 120, 220, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/Pizza.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 40, 60, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/DESFENFOQUE.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarPizzaActionPerformed
        try {
            String nombre = this.jTextField1.getText();
            String ingredientes = this.jTextField2.getText();
            
            PizzaVo pizza = new PizzaVo(nombre,ingredientes);
            PizzaDAO pizzao  = new PizzaDAO();
                                         
            pizzao.guardar(Conexion.obtener(), pizza);
            JOptionPane.showMessageDialog(this, "Pizza ingresada correctamente");
            limpiar();
                  
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(RegistroPizza.class.getName()).log(Level.SEVERE, null, ex);
            
            JOptionPane.showMessageDialog(this, "ERROR");
        }
        
        
    }//GEN-LAST:event_RegistrarPizzaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegistrarPizza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        
        this.jTextField1.setText("");
        this.jTextField2.setText("");
        
    }
}
