/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.DAO.Conexion;
import Modelo.DAO.IngredienteDAO;
import Modelo.Vo.IngredienteVo;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public class RegistroIngrediente extends javax.swing.JFrame {

    /**
     * Creates new form RegistroIngrediente
     */
    public RegistroIngrediente() {
        initComponents();
        this.setTitle("REGISTRO INGREDIENTE");
        this.setSize(500,400);
        this.setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/Vista/imagenes/iconos/ingrediente_1.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        registrarIngrediente = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel5.setBackground(new java.awt.Color(0, 255, 0));
        jLabel5.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("REGISTRO INGREDIENTE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 60, 330, 46);

        jLabel7.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel7.setText("Nombre");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 120, 90, 21);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 120, 240, 30);

        registrarIngrediente.setBackground(new java.awt.Color(153, 153, 153));
        registrarIngrediente.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        registrarIngrediente.setText("Registrar");
        registrarIngrediente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarIngredienteActionPerformed(evt);
            }
        });
        getContentPane().add(registrarIngrediente);
        registrarIngrediente.setBounds(130, 220, 240, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(130, 170, 240, 30);

        jLabel8.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel8.setText("Precio");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 170, 90, 21);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/ingredientes.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 130, 120, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/DESFENFOQUE.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarIngredienteActionPerformed
        try {
            String nombre = this.jTextField1.getText();
            Short precio = Short.parseShort(this.jTextField2.getText());
            IngredienteVo ingrediente = new IngredienteVo(nombre,precio);
            
            IngredienteDAO ingredienteao = new IngredienteDAO();
            ingredienteao.guardar(Conexion.obtener(), ingrediente);
            JOptionPane.showMessageDialog(this, "Ingrediente "+nombre+" agregado correctamente");
            limpiar();
        } catch (SQLException | ClassNotFoundException ex) {
                        JOptionPane.showMessageDialog(this, "ERROR");

            System.out.println(ex.getMessage());
        }
        

    }//GEN-LAST:event_registrarIngredienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroIngrediente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton registrarIngrediente;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {

        
        this.jTextField1.setText("");
        this.jTextField2.setText("");
        
      }
}
